clusterGroup:
  name: prod

  namespaces:
    - rhoai-maas
    - cert-manager-operator
    - openshift-lws-operator
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - kuadrant-system:
        operatorGroup: true
        targetNamespaces: []

  subscriptions:
    cert-manager:
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
      channel: stable-v1
    lws:
      name: leader-worker-set
      namespace: openshift-lws-operator
      channel: stable-v1.0
    connectivity-link:
      name: rhcl-operator
      namespace: kuadrant-system
      csv: rhcl-operator.v1.2.1
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable-3.x

  applications:
    dsc:
      name: dsc
      namespace: rhoai-maas
      path: charts/dsc
    gateway:
      name: gateway
      namespace: rhoai-maas
      path: charts/gateway
    kuadrant:
      name: kuadrant
      namespace: rhoai-maas
      path: charts/kuadrant
    odh-dashboard:
      name: odh-dashboard
      namespace: rhoai-maas
      path: charts/odh-dashboard
    lws:
      name: lws
      namespace: openshift-lws-operator
      path: charts/lws
    cpu-inference-service:
      name: cpu-inference-service
      namespace: rhoai-maas
      path: charts/llm
      extraValueFiles:
        - /overrides/cpu-inference-service.yaml
