clusterGroup:
  name: prod

  namespaces:
    - openshift-lws-operator
    - vault
    - golang-external-secrets
    - cert-manager-operator:
        operatorGroup: true
        targetNamespaces: []
    - redhat-ods-operator:
        operatorGroup: true
        targetNamespaces: []
    - kuadrant-system:
        operatorGroup: true
        targetNamespaces: []

  subscriptions:
    cert-manager:
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
      channel: stable-v1
    lws:
      name: leader-worker-set
      namespace: openshift-lws-operator
      channel: stable-v1.0
    connectivity-link:
      name: rhcl-operator
      namespace: kuadrant-system
      csv: rhcl-operator.v1.2.1
    rhoai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: stable-3.x

  applications:
    golang-external-secrets:
      name: golang-external-secrets
      namespace: golang-external-secrets
      chart: golang-external-secrets
      chartVersion: 0.1.*
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
    rhoai-scaffolding:
      name: rhoai-scaffolding
      path: charts/rhoai-scaffolding
      syncPolicy:
        automated: {}
        retry:
          limit: 20
        syncOptions:
          - SkipDryRunOnMissingResource=true # OdhDashboardConfig CRD will not exists until default-dsc is installed
    networking:
      name: networking
      path: charts/networking
    user-management:
      name: user-management
      path: charts/user-management
    premium-inference-service:
      name: premium-inference-service
      path: charts/llm
      extraValueFiles:
        - /overrides/premium-inference-service.yaml
