apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    alpha.maas.opendatahub.io/tiers: '[]'
    opendatahub.io/model-type: generative
    openshift.io/display-name: qwen-cpu
  name: qwen-cpu
  namespace: rhoai-maas
  labels:
    opendatahub.io/dashboard: 'true'
    opendatahub.io/genai-asset: 'true'
spec:
  model:
    name: qwen-cpu
    uri: hf://Qwen/Qwen2.5-1.5B-Instruct
  replicas: 1
  router:
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
    route: {}
    scheduler: {}
  template:
    containers:
    - name: main
      image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:latest
      env:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "6"
        - name: ONEDNN_MAX_CPU_ISA
          value: "AVX512_CORE"
      command:
        - vllm
        - serve
      args:
        - /mnt/models
        - --max-model-len
        - "8192"
        - --ssl-keyfile
        - /var/run/kserve/tls/tls.key
        - --ssl-certfile
        - /var/run/kserve/tls/tls.crt
        - --dtype
        - float16
        - --kv-cache-dtype
        - fp16
        - --enforce-eager
      readinessProbe:
        httpGet:
          path: /health
          port: 8000
          scheme: HTTPS
        initialDelaySeconds: 90
        periodSeconds: 10
        failureThreshold: 18
      livenessProbe:
        httpGet:
          path: /health
          port: 8000
          scheme: HTTPS
        initialDelaySeconds: 180
        periodSeconds: 30
        timeoutSeconds: 20
      resources:
        limits:
          cpu: "4"
          memory: 24Gi
        requests:
          cpu: "4"
          memory: 24Gi
