apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    alpha.maas.opendatahub.io/tiers: '[]'
    opendatahub.io/model-type: generative
    openshift.io/display-name: granite-4-micro
  name: granite-4-micro
  namespace: rhoai-maas
  labels:
    opendatahub.io/dashboard: 'true'
spec:
  model:
    name: granite-4-micro
    uri: hf://ibm-granite/granite-4.0-micro
  replicas: 1
  router:
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
    route: {}
    scheduler: {}
  template:
    containers:
    - name: main
      image: public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo:latest
      env:
        - name: VLLM_CPU_KVCACHE_SPACE
          value: "8"
      cmd:
        - vllm
        - serve
      args:
        - --max-model-len
        - "16384"
      resources:
        limits:
          cpu: "4"
          memory: 16Gi
        requests:
          cpu: "4"
          memory: 16Gi
