apiVersion: serving.kserve.io/v1alpha1
kind: LLMInferenceService
metadata:
  annotations:
    alpha.maas.opendatahub.io/tiers: '{{ toJson .Values.maas.tiers }}'
    opendatahub.io/model-type: generative
    openshift.io/display-name: {{ .Values.name }}
    {{- if not .Values.auth.enabled }}
    security.opendatahub.io/enable-auth: "false"
    {{- end }}
  name: {{ .Values.name }}
  labels:
    opendatahub.io/dashboard: 'true'
    # opendatahub.io/genai-asset: 'true'
spec:
  model:
    name: {{ .Values.name }}
    uri: {{ printf "hf://%s" .Values.model }}
  replicas: 1
  router:
    gateway:
      refs:
        - name: maas-default-gateway
          namespace: openshift-ingress
    route: {}
    scheduler: {}
  template:
    containers:
    - name: main
      {{- with .Values.runtimeContainer.image }}
      image: {{ . }}
      {{- end }}
      {{- with .Values.runtimeContainer.env }}
      env:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtimeContainer.command }}
      command:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtimeContainer.args }}
      args:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtimeContainer.readinessProbe }}
      readinessProbe:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtimeContainer.livenessProbe }}
      livenessProbe:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtimeContainer.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
