name: llm-inference-service
model: ibm-granite/granite-4.0-1b

maas:
  tiers: []

auth:
  enabled: true

runtimeContainer:
  image: ""
  env: {}
  command: {}
  args: {}
  readinessProbe: {}
  livenessProbe: {}
  resources: {}
