apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    {{- with .Values.dsc.components }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
