apiVersion: datasciencecluster.opendatahub.io/v2
kind: DataScienceCluster
metadata:
  name: default-dsc
spec:
  components:
    kserve:
      managementState: Managed
      modelsAsService:
        managementState: Managed
      nim:
        managementState: Managed
      rawDeploymentServiceConfig: Headed
    modelregistry:
      registriesNamespace: rhoai-model-registries
    feastoperator: {}
    trustyai:
      eval:
        lmeval:
          permitCodeExecution: deny
          permitOnline: deny
    aipipelines: {}
    ray: {}
    kueue:
      defaultClusterQueueName: default
      defaultLocalQueueName: default
    workbenches:
      workbenchNamespace: rhods-notebooks
    mlflowoperator: {}
    dashboard:
      managementState: Managed
    trainer: {}
    llamastackoperator:
      managementState: Managed
    trainingoperator: {}
