{{- if .Values.idp.github.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-oauth-app
  namespace: openshift-config
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-secret
    template:
      type: Opaque
      engineVersion: v2
      data:
        clientSecret: "{{ `{{ .client_secret }}` }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: secret/data/hub/gh-oauth
      property: client_secret
---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: {{ .Values.idp.github.name }}
    mappingMethod: claim
    type: GitHub
    github:
      clientID: {{ .Values.idp.github.clientId }}
      clientSecret:
        name: github-secret
      {{- with .Values.idp.github.organizations }}
      organizations:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with .Values.idp.github.teams }}
      teams:
        {{- toYaml . | nindent 8}}
      {{- end }}
{{- end }}
